
/**
 * Generates default Next.js files when not present in the original project
 */
import { ConversionOutput } from './types';
import { logConversion } from './logger';

/**
 * Create required Next.js files if they don't exist already
 */
export const createDefaultFiles = (result: ConversionOutput): void => {
  // Check if there are any user-provided files
  const hasUserPages = Object.keys(result.pages).length > 0;
  const hasUserComponents = Object.keys(result.components).length > 0;
  const hasUserApiRoutes = Object.keys(result.api).length > 0;
  
  // Only create default pages if no pages exist at all
  if (!result.pages['index.js'] && !result.pages['index.tsx'] && !hasUserPages) {
    result.pages['index.js'] = `import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Next.js App</title>
        <meta name="description" content="Generated by Next.js conversion" />
      </Head>
      <main className="container mx-auto px-4 py-8">
        <h1 className="text-3xl font-bold mb-4">Welcome to your Next.js App</h1>
        <p className="mb-4">This app was converted from React to Next.js</p>
        <p className="mb-6">It looks like no files were provided for conversion. Please try again with your React project files.</p>
        
        <div className="p-4 border border-gray-200 rounded-md bg-gray-50 mb-6">
          <h2 className="text-xl font-semibold mb-2">Getting Started</h2>
          <p>To see the converter in action:</p>
          <ol className="list-decimal pl-6 mt-2 space-y-1">
            <li>Upload your React project files</li>
            <li>Make sure to include your main components and pages</li>
            <li>Include package.json to analyze dependencies</li>
          </ol>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Link href="/about" className="p-4 border border-blue-200 rounded-md bg-blue-50 hover:bg-blue-100 transition-colors">
            <h3 className="text-lg font-medium mb-1">About Page</h3>
            <p className="text-sm text-gray-600">View the sample about page created during conversion</p>
          </Link>
          
          <Link href="/api/hello" className="p-4 border border-green-200 rounded-md bg-green-50 hover:bg-green-100 transition-colors">
            <h3 className="text-lg font-medium mb-1">API Route</h3>
            <p className="text-sm text-gray-600">See a sample Next.js API route</p>
          </Link>
        </div>
      </main>
    </>
  );
}`;
    logConversion('info', 'Created default index page');
    
    // Only create example pages if no user pages exist
    if (!hasUserPages) {
      // Add example about page
      result.pages['about.js'] = `import Head from 'next/head';
import Link from 'next/link';

export default function About() {
  return (
    <>
      <Head>
        <title>About | Next.js App</title>
        <meta name="description" content="About this Next.js application" />
      </Head>
      <main className="container mx-auto px-4 py-8">
        <h1 className="text-3xl font-bold mb-4">About this App</h1>
        <p className="mb-6">This is an example about page generated during Next.js conversion.</p>
        
        <div className="mb-6">
          <h2 className="text-xl font-semibold mb-2">Next.js Features</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>File-based routing</li>
            <li>Server-side rendering</li>
            <li>Static site generation</li>
            <li>API Routes</li>
            <li>Built-in Image optimization</li>
          </ul>
        </div>
        
        <Link href="/" className="text-blue-500 hover:underline">
          ← Back to Home
        </Link>
      </main>
    </>
  );
}`;
      logConversion('info', 'Created example about page');
    }
    
    // Only create API route if no user API routes exist
    if (!hasUserApiRoutes) {
      // Add example API route
      result.api['hello.js'] = `export default function handler(req, res) {
  res.status(200).json({ 
    message: 'Hello from the API!',
    timestamp: new Date().toISOString()
  });
}`;
      logConversion('info', 'Created example API route');
    }
  }
  
  // Create _app.js if not already created - this is essential for Next.js
  if (!result.pages['_app.js'] && !result.pages['_app.tsx']) {
    result.pages['_app.js'] = `import '../styles/globals.css';

function MyApp({ Component, pageProps }) {
  return (
    <div className="min-h-screen flex flex-col">
      <header className="bg-gray-800 text-white p-4">
        <div className="container mx-auto flex justify-between items-center">
          <h1 className="font-bold text-xl">Next.js App</h1>
          <nav>
            <ul className="flex space-x-4">
              <li><a href="/" className="hover:text-gray-300">Home</a></li>
              <li><a href="/about" className="hover:text-gray-300">About</a></li>
            </ul>
          </nav>
        </div>
      </header>
      
      <main className="flex-grow">
        <Component {...pageProps} />
      </main>
      
      <footer className="bg-gray-100 p-4 text-center text-gray-600 text-sm">
        <div className="container mx-auto">
          Converted from React to Next.js
        </div>
      </footer>
    </div>
  );
}

export default MyApp;`;
    logConversion('info', 'Created default _app page');
  }
  
  // Add 404 page only if needed
  if (!result.pages['404.js'] && !result.pages['404.tsx'] && !hasUserPages) {
    result.pages['404.js'] = `import Head from 'next/head';
import Link from 'next/link';

export default function NotFound() {
  return (
    <>
      <Head>
        <title>404 - Page Not Found</title>
        <meta name="description" content="Page not found" />
      </Head>
      <div className="flex flex-col items-center justify-center min-h-screen text-center px-4 py-16">
        <h1 className="text-6xl font-bold mb-4">404</h1>
        <p className="text-xl mb-8">Oops! The page you're looking for doesn't exist.</p>
        <Link href="/" className="text-blue-500 hover:underline">
          Go back home
        </Link>
      </div>
    </>
  );
}`;
    logConversion('info', 'Created 404 page');
  }
  
  // Add global styles if not present
  if (!result.styles['globals.css']) {
    result.styles['globals.css'] = `html,
body {
  padding: 0;
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
    Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
}

a {
  color: inherit;
  text-decoration: none;
}

* {
  box-sizing: border-box;
}

.container {
  width: 100%;
  margin-left: auto;
  margin-right: auto;
  padding-left: 1rem;
  padding-right: 1rem;
}

@media (min-width: 640px) {
  .container {
    max-width: 640px;
  }
}

@media (min-width: 768px) {
  .container {
    max-width: 768px;
  }
}

@media (min-width: 1024px) {
  .container {
    max-width: 1024px;
  }
}

@media (min-width: 1280px) {
  .container {
    max-width: 1280px;
  }
}

@media (prefers-color-scheme: dark) {
  html {
    color-scheme: dark;
  }
  body {
    color: white;
    background: black;
  }
}`;
    logConversion('info', 'Created global stylesheet');
  }
  
  // Create README with conversion notes - always helpful for users
  result.config['README.md'] = `# Next.js Converted Project

This project was automatically converted from React to Next.js using NextForge.

## Getting Started

First, run the development server:

\`\`\`bash
npm run dev
# or
yarn dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

## Project Structure

${hasUserPages ? '- Your React pages have been converted to Next.js pages' : '- Default Next.js pages have been created'}
${hasUserComponents ? '- Your React components have been preserved and adapted' : ''}
${hasUserApiRoutes ? '- Your API endpoints have been converted to Next.js API routes' : ''}

## Learn More

To learn more about Next.js, take a look at the following resources:

- [Next.js Documentation](https://nextjs.org/docs)
- [Learn Next.js](https://nextjs.org/learn)
- [Next.js GitHub Repository](https://github.com/vercel/next.js/)
`;
  logConversion('success', 'Created README with conversion notes');
};
